# =============================================================================
# docker-compose.yml
# Orquestación del contenedor del modelo de créditos
# =============================================================================

version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Users\Manuela\cdp_proyecto:/var/jenkins_home/workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
volumes:
  jenkins_home: {}