sonar.projectKey=manugomez1206_cdp_proyecto
sonar.organization=manugomez1206
sonar.projectName=cdp_proyecto
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11